# Generated by Django 4.2.3 on 2023-08-24 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='address_delivery', to='account.address', verbose_name='delivery_address'),
            preserve_default=False,
        ),
    ]
