# Generated by Django 4.2.3 on 2023-07-23 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_basket_status_wishlist_order_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-pk'], 'verbose_name': 'user_address', 'verbose_name_plural': 'addresses'},
        ),
        migrations.AlterModelOptions(
            name='basket',
            options={'ordering': ['-pk'], 'verbose_name': 'product_to_basket', 'verbose_name_plural': 'products_to_basket'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-pk'], 'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'status', 'verbose_name_plural': 'statuses'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['pk'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['-pk'], 'verbose_name': 'users_wish', 'verbose_name_plural': 'wishlists'},
        ),
    ]
