# Generated by Django 4.2.3 on 2023-09-26 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttobasket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_basket', to=settings.AUTH_USER_MODEL),
        ),
    ]
