# Generated by Django 4.2.3 on 2023-10-07 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_alter_image_variant_alter_varianttostore_store'),
        ('account', '0005_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttobasket',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variantinbasket', to='product.variant', verbose_name='Variant'),
        ),
    ]
