# Generated by Django 4.2.3 on 2023-11-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bloger',
            field=models.BooleanField(default=False, verbose_name='bloger'),
        ),
        migrations.AlterField(
            model_name='user',
            name='deleted_at',
            field=models.BooleanField(default=False, verbose_name='delete account'),
        ),
        migrations.AlterField(
            model_name='user',
            name='saller',
            field=models.BooleanField(default=False, verbose_name='seller'),
        ),
    ]
