version: '3.1'

services:

  db:
    image: postgres
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_USER: Pavshop
      POSTGRES_PASSWORD: P@vshop2023
      POSTGRES_DB: pav
      PGDATA: ~/E-commerce-Pavshop-PyA3/
      POSTGRES_INITDB_ARGS: "-A md5"
    ports:
      - "5432:5432"
    volumes:
      - /postgres_volume:/var/lib/postgresql/data
      # - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    # volumes:
    #   - 

  
  redis:
    image: redis
    ports:
      - "6379:6379"
  
  # volumes:
  #   - dojango_volume:./django_volume
