version: '3.1'

services:

  db:
    image: postgres
    restart: always
    container_name: postgres
    ports:
     - 5432:5432
    environment:
      POSTGRES_USER: Pavshop
      POSTGRES_PASSWORD: P@wshop2023
      POSTGRES_DB: pav
      PGDATA: ~/E-commerce-Pavshop-PyA3/
      POSTGRES_INITDB_ARGS: "-A md5"
    volumes:
<<<<<<< HEAD
      - ./:/var/lib/postgresql/data \
=======
      - ./pavdata:var/lib/postgresql

>>>>>>> yusif
