version: '3.1'

services:

  db:
    image: postgres
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_USER: Pavshop
      POSTGRES_PASSWORD: P@wshop2023
      POSTGRES_DB: pav
      PGDATA: ~/E-commerce-Pavshop-PyA3/
      POSTGRES_INITDB_ARGS: "-A md5"
    ports:
      - "54321:5432"
