# Generated by Django 4.2.3 on 2023-07-23 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-pk'], 'verbose_name': 'contact', 'verbose_name_plural': 'contacts'},
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ['pk'], 'verbose_name': 'subscriber', 'verbose_name_plural': 'subscribers'},
        ),
    ]
