# Generated by Django 4.2.3 on 2023-08-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='create at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='update at')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='slider name')),
                ('slide', models.ImageField(upload_to='slide_image/', verbose_name='slide')),
                ('first_line', models.CharField(max_length=50, verbose_name='first line')),
                ('second_line', models.CharField(max_length=50, verbose_name='second line')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='price')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
