# Generated by Django 4.2.3 on 2023-08-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_homeslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslider',
            name='published_at',
            field=models.BooleanField(default=False),
        ),
    ]
