# Generated by Django 4.2.3 on 2023-07-23 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['title'], 'verbose_name': 'brand', 'verbose_name_plural': 'brands'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['brand_id'], 'verbose_name': 'collection', 'verbose_name_plural': 'collections'},
        ),
        migrations.AlterModelOptions(
            name='designer',
            options={'ordering': ['name'], 'verbose_name': 'designer', 'verbose_name_plural': 'designers'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['-pk'], 'verbose_name': 'discont', 'verbose_name_plural': 'disconts'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-pk'], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['pk'], 'verbose_name': 'review', 'verbose_name_plural': 'reviews'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['title'], 'verbose_name': 'store', 'verbose_name_plural': 'stores'},
        ),
        migrations.AlterModelOptions(
            name='style',
            options={'ordering': ['title'], 'verbose_name': 'style', 'verbose_name_plural': 'styles'},
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'ordering': ['title'], 'verbose_name': 'variant', 'verbose_name_plural': 'variants'},
        ),
        migrations.AddField(
            model_name='variant',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.unit'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.ImageField(upload_to='product_images/'),
        ),
        migrations.RemoveField(
            model_name='variant',
            name='image_id',
        ),
        migrations.AddField(
            model_name='variant',
            name='image_id',
            field=models.ManyToManyField(to='product.image'),
        ),
    ]
