# Generated by Django 4.2.3 on 2023-07-26 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link='parents', related_name='parents', to='product.category'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='types', to='product.discounttype'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='brandsp', to='product.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categoriesp', to='product.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='collection_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collectionsp', to='product.collection'),
        ),
        migrations.AlterField(
            model_name='product',
            name='style_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stylesp', to='product.style'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productsr', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userspr', to=settings.AUTH_USER_MODEL),
        ),
    ]
