# Generated by Django 4.2.3 on 2023-08-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='parent',
            field=models.ManyToManyField(blank=True, to='product.product'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='parent',
            field=models.ManyToManyField(blank=True, to='product.variant'),
        ),
        migrations.AlterField(
            model_name='varianttostore',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
