# Generated by Django 4.2.3 on 2023-08-24 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_alter_product_parent_alter_variant_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='user_add_variant', to=settings.AUTH_USER_MODEL, verbose_name='variant_creator'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_add_image', to=settings.AUTH_USER_MODEL, verbose_name='creater'),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_add_product', to=settings.AUTH_USER_MODEL, verbose_name='product_creator'),
        ),
    ]
