# Generated by Django 4.2.3 on 2023-08-24 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_designer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link='review', to='product.productreview'),
        ),
    ]
