# Generated by Django 4.2.3 on 2023-08-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_productreview_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='discount_size',
            new_name='discount_persent',
        ),
        migrations.AddField(
            model_name='discount',
            name='price_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
