# Generated by Django 4.2.3 on 2023-08-24 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_discount_size_discount_discount_persent_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='discount',
            name='persent',
        ),
        migrations.AlterField(
            model_name='discount',
            name='other_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.CheckConstraint(check=models.Q(('discount_persent__lte', 100)), name='persent'),
        ),
    ]
