# Generated by Django 4.2.3 on 2023-08-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_discount_persent_alter_discount_other_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='price_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
