# Generated by Django 4.2.3 on 2023-08-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_discount_price_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='deleted_at',
            field=models.BooleanField(default=False),
        ),
    ]
