# Generated by Django 4.2.3 on 2023-08-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_store_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='deleted_at',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collection',
            name='deleted_at',
            field=models.BooleanField(default=False),
        ),
    ]
