# Generated by Django 4.2.3 on 2023-08-26 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_brand_deleted_at_collection_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantofproduct', to='product.product'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='variant_tag', to='product.tag'),
        ),
    ]
