# Generated by Django 4.2.3 on 2023-08-26 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_variant_product_id_alter_variant_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='image_id',
        ),
        migrations.AddField(
            model_name='variant',
            name='image_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.image', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
