# Generated by Django 4.2.3 on 2023-08-26 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_variant_image_id_variant_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='image_id',
        ),
    ]
