# Generated by Django 4.2.3 on 2023-08-26 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_remove_variant_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.variant', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
