# Generated by Django 4.2.3 on 2023-08-27 07:16

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_image_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='published_at',
            field=models.BooleanField(default=False, verbose_name='published at Coll'),
        ),
        migrations.AddField(
            model_name='variant',
            name='in_stock',
            field=models.BooleanField(default=False, verbose_name='In stock'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link='parents', related_name='parents', to='product.category'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantofproduct', to='product.product', verbose_name='product id'),
        ),
    ]
