# Generated by Django 4.2.3 on 2023-08-30 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_category_options_category_level_category_lft_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
    ]
