# Generated by Django 4.2.3 on 2023-09-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_persent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.CheckConstraint(check=models.Q(('date_begin__lt', models.F('date_end'))), name='discount_time'),
        ),
    ]
