# Generated by Django 4.2.3 on 2023-09-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_discount_discount_persent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='discount_id',
            field=models.ManyToManyField(blank=True, related_name='discounts', to='product.discount', verbose_name='Discont'),
        ),
    ]
