# Generated by Django 4.2.3 on 2023-10-02 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_alter_variant_discount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='variant',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='product.variant', verbose_name='Image'),
        ),
    ]
