# Generated by Django 4.2.3 on 2023-10-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_alter_image_variant_alter_varianttostore_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=150, null=True, unique=True),
        ),
    ]
