# Generated by Django 4.2.3 on 2023-11-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_alter_variant_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='image',
            field=models.ImageField(null=True, upload_to='designer_image/', verbose_name='designer photo'),
        ),
    ]
