# Generated by Django 4.2.3 on 2023-08-21 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='create at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='update at')),
                ('title', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('text', models.TextField(verbose_name='Content')),
                ('Preview', models.ImageField(upload_to='blog_image/', verbose_name='Preview')),
                ('published_at', models.BooleanField(default=False, verbose_name='Published at')),
                ('deleted_at', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('image', models.ManyToManyField(to='product.image', verbose_name='Image')),
                ('tag', models.ManyToManyField(to='product.tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='create at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='update at')),
                ('text', models.TextField(verbose_name='')),
                ('deleted_at', models.BooleanField(default=False)),
                ('post', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='post', to='blog.post')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewsr', to='blog.postreview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userrew', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
                'ordering': ['pk'],
            },
        ),
    ]
