# Generated by Django 4.2.3 on 2023-07-26 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorsp', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ManyToManyField(related_name='imagesp', to='blog.image', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='postreview',
            name='post',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='postsr', to='blog.post'),
        ),
        migrations.AlterField(
            model_name='postreview',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewsr', to='blog.postreview'),
        ),
        migrations.AlterField(
            model_name='postreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usersr', to=settings.AUTH_USER_MODEL),
        ),
    ]
