# Generated by Django 4.2.3 on 2023-07-23 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['pk'], 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.AlterModelOptions(
            name='postreview',
            options={'ordering': ['pk'], 'verbose_name': 'postreview', 'verbose_name_plural': 'reviews of posts'},
        ),
        migrations.AddField(
            model_name='postreview',
            name='review_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.postreview'),
        ),
        migrations.AlterField(
            model_name='postreview',
            name='post',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='blog.post'),
        ),
        migrations.AlterField(
            model_name='postreview',
            name='review',
            field=models.TextField(),
        ),
    ]
