# Generated by Django 4.2.3 on 2023-08-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_productreview_review'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(blank=True, to='product.category', verbose_name='About Categories'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ManyToManyField(blank=True, to='product.image', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='product',
            field=models.ManyToManyField(blank=True, to='product.product', verbose_name='About Products'),
        ),
    ]
