# Generated by Django 4.2.3 on 2023-10-26 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_alter_image_variant_alter_varianttostore_store'),
        ('blog', '0003_alter_post_category_alter_post_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Preview',
            new_name='preview',
        ),
        migrations.AlterField(
            model_name='post',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='productsofpost', to='product.product', verbose_name='About Products'),
        ),
        migrations.AlterField(
            model_name='postreview',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='postreview', to='blog.postreview'),
        ),
    ]
