# Generated by Django 4.2.3 on 2023-11-16 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_preview_post_preview_alter_post_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreview',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='postreviewrel', to='blog.postreview'),
        ),
    ]
