# Generated by Django 4.2.3 on 2023-11-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_postreview_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreview',
            name='text',
            field=models.TextField(verbose_name='review_text'),
        ),
    ]
